### ISSUE TITLE
Dictionary-issue after using the snippet

### ISSUE THREAD

**Issue by enkelmedia** [Flaeng/Umbraco.EditButton#1]
When I used this on a Umbraco 7.15.3-site my dictionary items was getting empty after using the script in the view. 

Turns out this row,

`
wrapper.GetCurrentIdentity(true);
`

In some way changed the "culture context" for the request to the culture of the backoffice user so that empty dictionaries was returned since we did not have a dictionary language for the language that my backoffice user was using.

Any way, after looking here https://our.umbraco.com/forum/umbraco-7/using-umbraco-7/72798-how-to-check-if-an-umbraco-user-is-logged-in-on-a-frontend-request

I change the code to check if a user is logged on in the backoffice to:

```
    var ticket = new System.Web.HttpContextWrapper(System.Web.HttpContext.Current).GetUmbracoAuthTicket();
    if (ticket != null)
    {
        isUmbracoLoggedIn = true;
    }
```

An now my dictionaries works as expected and the culture for the request is not changed.

**Comment by Flaeng** [comment]
Hey, thank you for posting this.
Not sure I'm gonna make a new package for Umbraco 7 with this fix since the project should work on Umbraco 8 with the latest updates. But thank you for posting it anyway - I hope that others with the same issues sees this :)
